spring.application.name=CourseRegistrationSystem
server.port=8080

spring.datasource.url=jdbc:oracle:thin:@192.168.0.195:1521:XE
spring.datasource.username=SYSTEM
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# HikariCP specific settings (optional, but good for connection logs)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000
